### ISSUE TITLE
System unresponsive after toggling item

### ISSUE THREAD

**Issue by krmax44** [geoph9/hass-gshell-extension#19]
After I click "Toggle XYZ", GNOME is frozen for a short moment (possibly until the request is completed?). See video below (I was constantly moving the mouse)

https://user-images.githubusercontent.com/12673799/130361773-df6405b4-4791-4531-8f84-0cc34bdefde3.mp4

**Comment by geoph9** [comment]
Hi and thank you for creating this issue!

I have also noticed this issue happening when the server takes too long to respond. The problem occurs when we use the `SoupSession` instance in order to send the message/request to the server ([see here](https://github.com/geoph9/hass-gshell-extension/blob/master/utils.js#L51)). The whole gnome-shell is blocked until we get a response.

A quick fix would be to reduce the timeout, but that is not a real solution. I would have to further read the documentation on `Soup`'s session management in order to solve this. I will try to do it in the near future (unless someone else solves it first!).

**Comment by geoph9** [comment]
Should be fixed by #62 . Please re-open if the issue persists.
