### ISSUE TITLE
Token is not persisted after the computer is restarted

### ISSUE THREAD

**Issue by Ombrelin** [geoph9/hass-gshell-extension#42]

**Comment by geoph9** [comment]
Hi, thanks for creating this, but it is not 100% clear what's the issue. Even if it was clear, I would not be able to help you since you haven't shared any info about your environment (most importantly: gnome version, os).

**Comment by Ombrelin** [comment]
Hello !
Here is the information : 
![image](https://user-images.githubusercontent.com/47502331/190922015-05d0224e-39d6-44ca-a263-cb925b579927.png)

The issue is, when I add my HA token, the extension works perfectly, but after I restart, the token is gone and I can't access my entities anymore : 
![image](https://user-images.githubusercontent.com/47502331/190922074-c7b02b06-6b2e-49e4-999c-da6a749ed405.png)

**Comment by geoph9** [comment]
Hi, gnome 42 apparently has some issues (see #30 and #43). Could you please follow the instructions on #43 and post the traceback for `hass-gshell-extension`?

**Comment by Ombrelin** [comment]
Hi, thank you for your answer. I followed the mentioned instructions, however I can see no `hass-gshell-extension` entries in the logs

**Comment by geoph9** [comment]
Right, my logging functions are pretty bad and if no error occurs, it is not clear whether a message belongs to this extension or not.

Just to be clear, by saying that the access token is "gone" do you mean that it is not visible on the field? Because that was actually intended (bad UI, I know I know) for security reasons.

By "accessing your entities", do you mean that they don't appear on the menu? How about the "Togglables" section of the preferences? Can you see them there and activate them?

**Comment by Ombrelin** [comment]
I tried to reproduce the issue today, but everything is working fine for now, you must have fixed it in a recent release 🙌
I'll re-open if I experience this issue again.
Thank you for the very usefull tool !
