### ISSUE TITLE
Build script references a different filename than current releases

### ISSUE THREAD

**Issue by Peter200lx** [geoph9/hass-gshell-extension#72]
Both versions 44 and 45 have a filename like:
https://github.com/geoph9/hass-gshell-extension/releases/download/45/hass-gshell@geoph9.zip
instead of what the build script looks for of `hass-gshell@geoph9-on-github.shell-extension.zip`

https://github.com/geoph9/hass-gshell-extension/blob/c2d0236a71e441ca9c0694855f5da15aa0f8a9cb/build.sh#L41

Either the releases should be updated to have the correct filenames or the script should try both I believe

(As a note, I'm trying the build script as the Gnome 45 release still hasn't been updated to https://extensions.gnome.org/extension/4170/home-assistant-extension/ )

**Comment by geoph9** [comment]
Hi @Peter200lx , thanks for noticing this! I'll make the necessary changes right away. I'll also try to republish the gnome 45 version at e.g.o (last time it was rejected because I failed to follow all of the [guidelines](https://gjs.guide/extensions/review-guidelines/review-guidelines.html#general-guidelines)).

**Comment by geoph9** [comment]
Building using `build.sh` should work now (I just changed the filenames of the releases so that I wouldn't have to make unnecessary url checks in the script).

I also uploaded the most recent version over at e.g.o. and I am awaiting for a review. I think my changes follow all new guidelines, but it's quite possible I might have missed some. In any case, I will be closing this now.
